# stole this from https://github.com/mrsauravsahu/mrss.api 😛😛
# TODO: Optimize image sizing

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# copy everything else and build
COPY . ./

RUN dotnet publish TemplateMonorepo.AspNetCoreService.csproj -c Release -r linux-x64 -o out /p:PublishSingleFile=True

# build runtime image
FROM mcr.microsoft.com/dotnet/runtime:5.0
WORKDIR /app
COPY --from=build-env /app/out ./

EXPOSE 80

ENTRYPOINT ./TemplateMonorepo.AspNetCoreService